repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
    -   id: no-commit-to-branch
        args: ['--branch=master']
    -   id: trailing-whitespace


