version: "3"

services:
  api:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS='*'
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    links:
      - db
    networks:
      - public
      - private

  db:
    image: mysql:5.7.27
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=api
    networks:
      - public
      - private
    volumes:
      - mysqldata:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

volumes:
  mysqldata:

networks:
  public:
  private:
