version: "3"

services:
  api:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS='*'
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    networks:
      - public
      - private

networks:
  public:
  private:
