# Generated by Django 2.2.4 on 2019-09-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(blank=True, null=True, verbose_name="number"),
                ),
                (
                    "short_text",
                    models.CharField(blank=True, max_length=30, verbose_name="char"),
                ),
                ("long_text", models.TextField(blank=True, verbose_name="text")),
                (
                    "some_date",
                    models.DateField(blank=True, null=True, verbose_name="some date"),
                ),
                (
                    "boolean",
                    models.BooleanField(default=False, verbose_name="true or false"),
                ),
            ],
            options={"verbose_name": "example", "verbose_name_plural": "examples"},
        )
    ]
